fix actions

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -22,7 +22,14 @@ jobs:
         run: |
           gh pr review --approve "$PR_URL"
           gh pr edit "$PR_URL" -t "(auto merged) $PR_TITLE"
-          gh pr merge --auto --merge "$PR_URL"
+
+          # Retry to work around "Base branch was modified." error.
+          # Ref: https://github.com/cli/cli/issues/8092
+          for i in {1..3}; do
+            gh pr merge --auto --merge "$PR_URL" && exit 0
+            sleep 5
+          done
+          exit 1
         env:
           PR_URL: ${{ github.event.pull_request.html_url }}
           PR_TITLE: ${{ github.event.pull_request.title }}
